apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-travel-planner-config
  namespace: default
data:
  MYSQL_HOST: mysql-service
  MYSQL_DATABASE: devops
  MYSQL_USER: ajit
  nginx.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://app-service:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
