apiVersion: v1
kind: Secret
metadata:
  name: ai-travel-planner-secrets
  namespace: default
type: Opaque
data:
  GOOGLE_API_KEY: QUl6YVN5QkgyQkhGZmFpNXFKendzRkgySzY4ZmJiZUxWYkdLMHVz
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_PASSWORD: YWppdA==
